### ISSUE TITLE
Subscriber optional context

### ISSUE THREAD

**Issue by cdomigan** [ReactTraining/react-broadcast#10]
Thanks for this library.

I'm wanting to use Subscriber, but in a place where the context (broadcast) is not always set. In this case I would like to use either a default prop, or simply undefined.

Currently I can't do this, and I get this error:
`browser.js:40 Uncaught Error: <Subscriber channel="filterStore"> must be rendered in the context of a <Broadcast channel="filterStore">`

**Comment by mjackson** [comment]
You can do this right now. In 57de4ff3cd9a157eebc9756d4ed6a794b7e7eada we made `context.broadcasts` optional, so you're probably just using an older version of the library.
