### ISSUE TITLE
RFC: Use <Subscriber render> instead of <Subscriber children>

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-broadcast#44]
I'm personally starting to prefer using `render` instead of `children` whenever I'm using a render prop. But that may just be me.

**Comment by j-f1** [comment]
👍 I feel like `children` should be reserved for JSX because that’s what you can put inside `<Component>...</Component>`.

**Comment by fatfisz** [comment]
I'd compare using function in `children` to using thunks in Redux - you don't get the actual child, but something that you can call to get the child.
In this sense it's natural that there cannot be any other child other than the one between the tags, whereas with the `render` prop it feels (IMO) like a second API to do the same thing, just like the explicit `children` prop (i.e. `<Compo children={something} />`).

I think using function-as-children shouldn't feel any different than using thunk-as-action. On the other hand, not everyone fancies Redux 😉

**Comment by mjackson** [comment]
I think we'll just leave it at `children` for now. That's sort of the universally expected "render prop".
