### ISSUE TITLE
Updating from the outside

### ISSUE THREAD

**Issue by josephrexme** [ReactTraining/react-broadcast#50]
Is there a way to update the broadcast value from a separate file. Perhaps inside a method? Having a broadcast set with channel and value, I think I'll like something like:

```js
// different class
import { Broadcast } from 'react-broadcast'

class Foo extend React.Component {
  someMethod() {
    Broadcast.update({name: 'Brendan Eich'})
  }
}
```

**Comment by josephrexme** [comment]
Asking about this because my current problem has been in my use for authentication. Where I store values in localStorage and some global states rely on those values. When a method changes the values and goes to a different route, the value remains unchanged until page is refreshed

**Comment by mjackson** [comment]
Your question is more a question about how to use React than it is about how to use this library. A broadcast's value is updated through its `<Broadcast value>` prop. When your app first initializes, pull the value from local storage and keep it in state. Then, as the value changes update your state and your `<Broadcast>` component should automatically get the new value.

**Comment by josephrexme** [comment]
Thank you.
