### ISSUE TITLE
Multiple values (channel) for the same Provider (Broadcast)

### ISSUE THREAD

**Issue by hatpick** [ReactTraining/react-broadcast#51]
Is it possible to provide multiple values (i.e. localization and theme) on the same Provider (Broadcast) or should I wrap two providers/consumers inside a single component to achieve this?

**Comment by j-f1** [comment]
You should be able to use an object as the provided value.

**Comment by mjackson** [comment]
@j-f1 is correct. Your value could just be `<Broadcast ... value={{ localization, theme }}>`.
