### ISSUE TITLE
Allow <Subscriber> to render out of context?

### ISSUE THREAD

**Issue by mjackson** [ReactTraining/react-broadcast#6]
I'm opening this issue to discuss the change made in 57de4ff3cd9a157eebc9756d4ed6a794b7e7eada. I assume it was made so we can render `<Link>`s in the router outside of the context of a `<Router>`, right @ryanflorence?

**Comment by ryanflorence** [comment]
yeah, maybe the commit message wasn't clear.

**Comment by mjackson** [comment]
No, the commit message was great :) Just wanted to track discussion here.
